title: Jakk design
description: >
  Jakk design portfolio

colors:
  - name: dark-grey
    R: 80
    G: 80
    B: 80
  - name: brown
    R: 61
    G: 54
    B: 51
  - name: mint
    R: 189
    G: 227 
    B: 188
  - name: light-grey
    R: 240
    G: 240
    B: 240
  - name: Beige
    R: 237
    G: 230
    B: 213
portfolio:
  - image: realism-1.png
    color: light-grey
    description: Pillow65 by Kelium Works
  - image: realism-2.png
    color: light-grey
    description: Koyu by Rama Works
  - image: kbdfans.png
    color: light-grey
    description: D60 Lite by KBDFans
  - image: the-key-company.png
    color: light-grey
    description: M0LLY By The Key Company
